### ISSUE TITLE
Implementa DELETE /api/users/{id}

### ISSUE THREAD

**Issue by sambrista** [fco-veragua/tweetfony#10]

**Comment by fco-veragua** [comment]
Completado.

**Comment by sambrista** [comment]
La ruta debería ser /api/users/{id}. En las APIs REST cada ruta o endpoint simboliza algo (/api/users es la lista de usuarios, y /api/users/25 es el usuario #25. Es con los métodos (GET, POST, DELETE... con lo que yo indico si quiero crear algo, consultarlo, borrarlo...).

**Comment by fco-veragua** [comment]
Corregido.

**Comment by sambrista** [comment]
Comprobado.
