### ISSUE TITLE
 Implementar GET /tweets y GET/users

### ISSUE THREAD

**Issue by sambrista** [fco-veragua/tweetfony#3]

**Comment by fco-veragua** [comment]
Completado.

**Comment by sambrista** [comment]
Los enlaces que das están mal. Si te fijas, cuando haces por ejemplo la lista de tweets estás haciendo una lista de enlaces a la ruta "api_get_tweets", cuando debería ser "api_get_tweet". El enlace que creas es por ejemplo "https://localhost:8000/api/tweets?id=4", y debería ser "https://localhost:8000/api/users/4".

**Comment by fco-veragua** [comment]
Corregido.

**Comment by sambrista** [comment]
Comprobado.

Si no hay tweets o no hay usuarios devuelves un error 404. Esto es correcto, pero quizás habría sido más elegante inicializar ``$result`` como un array vacío y no controlar si hay tweets o no:

```php
    function getTweets()
    {
        $entityManager = $this->getDoctrine();

        $tweets = $entityManager->getRepository(Tweet::class)->findAll();

        $result = array();

        foreach ($tweets as $tweet) {
            $result[] = $this->generateUrl('api_get_tweet', [
                'id' => $tweet->getId(),
            ], UrlGeneratorInterface::ABSOLUTE_URL);
        }
        return new JsonResponse($result);
    }
```

De esta manera, si hay tweets devolveremos la lista con los tweets y si no hay devolveremos la lista vacía.
