### ISSUE TITLE
Implementa el método postTweet(Request $request).

### ISSUE THREAD

**Issue by sambrista** [fco-veragua/tweetfony#4]

**Comment by fco-veragua** [comment]
Completado.

**Comment by sambrista** [comment]
- En tu código cuando creas un tweet, si el usuario indicado no existe, lanzas un error 409 diciendo que el usuario ya existe. Debería ser un 404 indicando que el usuario no ha sido encontrado.
- Por otro lado, la ruta debería ser /api/tweets. En las APIs REST cada ruta o endpoint simboliza algo (/api/tweets es la lista de tweets, y /api/tweets/25 es el tweet #25. Es con los métodos (GET, POST, DELETE... con lo que yo indico si quiero crear algo, consultarlo, borrarlo...).

**Comment by fco-veragua** [comment]
Corregido.

**Comment by sambrista** [comment]
Comprobado.
