### ISSUE TITLE
Implementa PUT /api/tweets/{id}

### ISSUE THREAD

**Issue by sambrista** [fco-veragua/tweetfony#8]

**Comment by fco-veragua** [comment]
Completado.

**Comment by sambrista** [comment]
La ruta debería ser /api/tweets/{id}. En las APIs REST cada ruta o endpoint simboliza algo (/api/tweets es la lista de tweets, y /api/tweets/25 es el tweet #25. Es con los métodos (GET, POST, DELETE... con lo que yo indico si quiero crear algo, consultarlo, borrarlo...).

**Comment by fco-veragua** [comment]
Corregido.

**Comment by sambrista** [comment]
Comprobado.
